name: Wheels Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - arch: x86_64
            os: Linux
            python: "3.9"
            link: https://github.com/disintar/ton/releases/download/ton-cpython-39--linux/
            file: python_ton.cpython-39-x86_64-linux-gnu.so

          - arch: x86_64
            os: Linux
            python: "3.10"
            link: https://github.com/disintar/ton/releases/download/ton-cpython-310--linux/
            file: python_ton.cpython-310-x86_64-linux-gnu.so

          - arch: x86_64
            os: Linux
            python: "3.11"
            link: https://github.com/disintar/ton/releases/download/ton-cpython-311--linux/
            file: python_ton.cpython-311-x86_64-linux-gnu.so

#          - arch: aarch64
#            os: macOS
#            python: "3.9"
#            link: https://github.com/disintar/ton/releases/download/ton-cpython-39-aarch64-darwin/
#            link: https://github.com/disintar/ton/releases/download/ton-x86_64-darwin-python-39/
#            file: python_ton.cpython-39-darwin.so

#          - arch: aarch64
#            os: macOS
#            python: "3.10"
#            link: https://github.com/disintar/ton/releases/download/ton-cpython-310-aarch64-darwin/
##            link: https://github.com/disintar/ton/releases/download/ton-x86_64-darwin-python-310/
#            file: python_ton.cpython-310-darwin.so
#
#          - arch: aarch64
#            os: macOS
#            python: "3.11"
#            link: https://github.com/disintar/ton/releases/download/ton-cpython-311-aarch64-darwin/
##           link: https://github.com/disintar/ton/releases/download/ton-x86_64-darwin-python-311/
#            file: python_ton.cpython-311-darwin.so

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
        env:
          USER: tvorogme

      - name: Install deps
        run: python -m pip install setuptools==68.0.0 build==0.10.0

      - name: Download prebuilt
        run: |
          curl {{ matrix.link }}${{ matrix.file }} --output ${{ matrix.file }} && mv ${{ matrix.file }} ./tonpy/libs/

      - name: Build wheel
        run: |
          python -m build --wheel --outdir dist/ .
          ls -lhta ./dist
          python rename_linux_dist.py

      - name: Store the binary wheel
        uses: actions/upload-artifact@v2
        with:
          name: python-package-distributions
          path: dist

  deploy:
    name: Publish 🐍📦 to PyPI
    runs-on: Linux
    needs:
      - build

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v2
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish distribution 📦 to PyPi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
